[tool.poetry]
name = "common-entity"
version = "0.1.0"
description = ""
authors = ["Jooho Lee <jhlee@si-analytics.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
protobuf = "^3.14.0"
grpcio = "^1.35.0"
grpcio-tools = "^1.35.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
