name: "($(Build.Reason))[$(SourceBranchName)]$(Date:yyyyMMdd).$(Rev:r)-$(BuildId)"

trigger:
  branches:
    include:
    - master
    - develop

variables:
  DOCKER_CONTEXT_PATH: '$(Build.SourcesDirectory)'
  DOCKERFILE_PATH: '$(DOCKER_CONTEXT_PATH)/Dockerfile'
  DOCKER_REGISTRY: 'docker.siadev.kr'
  DOCKER_PROJECT: 'dev'
  DOCKER_REPOSITORY: '$(DOCKER_PROJECT)/common-entity'
  DOCKER_BASE_IMAGE: 'docker.siadev.kr/sia/python:3.7.7-poetry'

jobs:
- job: python_ci_job
  displayName: Python CI
  pool:
    name: 'ubuntu18.04-cpu'
  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: Docker@2
    displayName: Log in to docker registry
    inputs:
      containerRegistry: $(DOCKER_REGISTRY)
      command: login

  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: '$(DOCKER_REGISTRY)'
      repository: '$(DOCKER_REPOSITORY)'
      command: 'build'
      Dockerfile: '$(DOCKERFILE_PATH)'
